# Generated by Django 3.2.7 on 2021-09-05 15:26

import django.contrib.postgres.indexes
import django.contrib.postgres.search
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vin', models.CharField(max_length=17, unique=True)),
                ('model', models.CharField(max_length=50)),
                ('make', models.CharField(max_length=50)),
                ('vehicle_type', models.CharField(blank=True, max_length=255)),
                ('year', models.PositiveIntegerField()),
                ('color', models.JSONField(blank=True, default=dict)),
                ('dimensions', models.JSONField(blank=True, default=dict)),
                ('weight', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('search_vector', django.contrib.postgres.search.SearchVectorField(blank=True, editable=False, null=True)),
            ],
            options={
                'verbose_name': 'Vehicle',
                'verbose_name_plural': 'Vehicles',
                'db_table': 'vehicles',
            },
        ),
        migrations.AddIndex(
            model_name='vehicle',
            index=models.Index(fields=['vin'], name='vehicles_vin_42311c_idx'),
        ),
        migrations.AddIndex(
            model_name='vehicle',
            index=models.Index(fields=['model'], name='vehicles_model_7ba64d_idx'),
        ),
        migrations.AddIndex(
            model_name='vehicle',
            index=models.Index(fields=['make'], name='vehicles_make_826314_idx'),
        ),
        migrations.AddIndex(
            model_name='vehicle',
            index=models.Index(fields=['vehicle_type'], name='vehicles_vehicle_d54349_idx'),
        ),
        migrations.AddIndex(
            model_name='vehicle',
            index=django.contrib.postgres.indexes.GinIndex(fields=['search_vector'], name='vehicles_search__6f2cca_gin'),
        ),
        migrations.AddIndex(
            model_name='vehicle',
            index=django.contrib.postgres.indexes.BrinIndex(fields=['created_at'], name='vehicles_created_d6b411_brin'),
        ),
    ]
